In [6]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 27, 28],
    'Score': [88.2, 92.6, 95.9, 70.4, 85.5],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Bangalore', 'Mumbai']
}
df = pd.DataFrame(data)
print(df)

      Name  Age  Score       City
0    Alice   25   88.2      Delhi
1      Bob   30   92.6     Mumbai
2  Charlie   35   95.9      Delhi
3    David   27   70.4  Bangalore
4      Eva   28   85.5     Mumbai


In [7]:
#Display the Dataframe Info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    5 non-null      object 
 1   Age     5 non-null      int64  
 2   Score   5 non-null      float64
 3   City    5 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes
None


In [8]:
#Summary Statistics
print(df.describe())

             Age      Score
count   5.000000   5.000000
mean   29.000000  86.520000
std     3.807887   9.857332
min    25.000000  70.400000
25%    27.000000  85.500000
50%    28.000000  88.200000
75%    30.000000  92.600000
max    35.000000  95.900000


In [13]:
#Check for missing values
print(df.isnull().sum())

Name     0
Age      0
Score    0
City     0
dtype: int64


In [15]:
#Simple Panda Series
x = [1.34, 7.12, 2.89]
myseries = pd.Series(x)
print(myseries)

0    1.34
1    7.12
2    2.89
dtype: float64


In [18]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print('Array:',arr)

Array: [1 2 3 4 5 6 7 8]


In [22]:
#Basic Statistical Analysis
data = np.array([1, 20, 3, 44, 59, 34, 67 ,11, 1001, 49, 4534])
print('Mean:',np.mean(data))
print('Median:',np.median(data))
print('Average:',np.average(data)) #mean and avg mean the same thing
print('Standard Deviation:',np.std(data))

Mean: 529.3636363636364
Median: 44.0
Average: 529.3636363636364
Standard Deviation: 1296.5221501965993


In [27]:
#Correaltion Coefficient
x = np.array([1, 2, 3])
y = np.array([-10, 20, -30])
correlation = np.corrcoef(x,y)
print("Correlation Coefficient: \n",correlation)


Correlation Coefficient: 
 [[ 1.         -0.39735971]
 [-0.39735971  1.        ]]


In [44]:
#Reshaping Arrays 
data = np.arange(24)
#print(data)
r = data.reshape(12,2)
#print(r)
r2 = data.reshape(6,4)
print(r2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [47]:
#Sorting Arrays
d1 = [12,342,31,46,15,26,787,38,9]
arr = np.array(d1)
sorted_d1 = np.sort(arr)
print("Sorted Array:",sorted_d1)


Sorted Array: [  9  12  15  26  31  38  46 342 787]
